name: rag
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - expat=2.5.0
  - faiss-cpu=1.8.0
  - filelock=3.13.1
  - jinja2=3.1.3
  - libcxx=14.0.6
  - libfaiss=1.8.0
  - libffi=3.4.4
  - libopenblas=0.3.21
  - llvm-openmp=14.0.6
  - markupsafe=2.1.3
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.1
  - ninja-base=1.10.2
  - nomkl=3.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.21
  - openblas-devel=0.3.21
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.11
  - pytorch=2.2.0
  - pyyaml=6.0.1
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - sympy=1.12
  - tk=8.6.12
  - typing_extensions=4.9.0
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - aiosqlite==0.20.0
      - annotated-types==0.6.0
      - anyio==4.3.0
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - bitarray==2.9.2
      - blinker==1.7.0
      - bs4==0.0.2
      - catalogue==2.0.10
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - chromedriver-autoinstaller==0.6.4
      - click==8.1.7
      - colbert-ai==0.2.19
      - cssselect==1.2.0
      - dataclasses-json==0.6.4
      - datasets==2.18.0
      - deprecated==1.2.14
      - dill==0.3.8
      - dirtyjson==1.0.8
      - distro==1.9.0
      - docx2txt==0.8
      - fastapi==0.110.0
      - feedfinder2==0.0.4
      - feedparser==6.0.11
      - flask==3.0.2
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - git-python==1.0.3
      - gitdb==4.0.11
      - gitpython==3.1.42
      - greenlet==3.0.3
      - h11==0.14.0
      - html2text==2020.1.16
      - httpcore==1.0.4
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.21.4
      - idna==3.6
      - itsdangerous==2.1.2
      - jieba3k==0.35.1
      - joblib==1.3.2
      - llama-index==0.10.20
      - llama-index-agent-openai==0.1.5
      - llama-index-cli==0.1.9
      - llama-index-core==0.10.20.post2
      - llama-index-embeddings-huggingface==0.1.4
      - llama-index-embeddings-openai==0.1.6
      - llama-index-indices-managed-llama-cloud==0.1.4
      - llama-index-legacy==0.9.48
      - llama-index-llms-openai==0.1.12
      - llama-index-multi-modal-llms-openai==0.1.4
      - llama-index-program-openai==0.1.4
      - llama-index-question-gen-openai==0.1.3
      - llama-index-readers-file==0.1.11
      - llama-index-readers-llama-parse==0.1.3
      - llama-index-readers-web==0.1.7
      - llama-parse==0.3.9
      - llamaindex-py-client==0.1.13
      - lxml==5.1.0
      - marshmallow==3.21.1
      - multidict==6.0.5
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - newspaper3k==0.2.8
      - ninja==1.11.1.1
      - nltk==3.8.1
      - openai==1.14.1
      - outcome==1.3.0.post0
      - packaging==24.0
      - pandas==2.2.1
      - pillow==10.2.0
      - playwright==1.42.0
      - pyarrow==15.0.1
      - pyarrow-hotfix==0.6
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pyee==11.0.1
      - pymupdf==1.23.26
      - pymupdfb==1.23.22
      - pypdf==4.1.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.1
      - regex==2023.12.25
      - requests==2.31.0
      - requests-file==2.0.0
      - safetensors==0.4.2
      - scipy==1.12.0
      - selenium==4.18.1
      - sgmllib3k==1.0.0
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - sqlalchemy==2.0.28
      - srsly==2.4.8
      - starlette==0.36.3
      - striprtf==0.0.26
      - tenacity==8.2.3
      - tiktoken==0.6.0
      - tinysegmenter==0.3
      - tldextract==5.1.2
      - tokenizers==0.15.2
      - tqdm==4.66.2
      - transformers==4.38.2
      - trio==0.25.0
      - trio-websocket==0.11.1
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - ujson==5.9.0
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - watchfiles==0.21.0
      - websockets==12.0
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - wsproto==1.2.0
      - xxhash==3.4.1
      - yarl==1.9.4
